"""empty message

Revision ID: 3bb8fa8ef2cb
Revises: 98a48b18dc1b
Create Date: 2019-10-22 11:53:05.303735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bb8fa8ef2cb'
down_revision = '98a48b18dc1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diarypost', sa.Column('featureImage', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diarypost', 'featureImage')
    # ### end Alembic commands ###
