"""empty message

Revision ID: 98a48b18dc1b
Revises: 
Create Date: 2019-10-22 09:59:43.976900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98a48b18dc1b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diarypost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('judul', sa.String(length=25), nullable=True),
    sa.Column('konten', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diarypost')
    # ### end Alembic commands ###
